version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/db/sql/users/init.sql:/docker-entrypoint-initdb.d/create_table.sql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - ./tmp/storages/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: always
    depends_on:
      - db

  api:
    container_name: users-api
    build:
      context: ./
    image: users-api
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: db
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"
    links:
      - db
    volumes:
      - "./:/app"
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db

volumes:
  db:
    driver: local
