export const users = [
  {
    fullname: "Jerome Hart",
    email: "jerome.hart@example.com",
    id: 1,
    login: "blueelephant640",
    phone: "021-522-4299",
    picture: "https://randomuser.me/api/portraits/men/19.jpg",
    age: 49,
    address: "78254 Ballybofey-Stranorlar Grafton Street",
    password: "vbnm",
    rating: 0,
  },
  {
    fullname: "Umut Özbir",
    email: "umut.ozbir@example.com",
    id: 2,
    login: "beautifulbutterfly192",
    phone: "(284)-356-2835",
    picture: "https://randomuser.me/api/portraits/men/75.jpg",
    age: 62,
    address: "38400 İzmir Anafartalar Cd",
    password: "antelope",
    rating: 0,
  },
  {
    fullname: "Sebastian Rasmussen",
    email: "sebastian.rasmussen@example.com",
    id: 3,
    login: "smallsnake448",
    phone: "91533630",
    picture: "https://randomuser.me/api/portraits/men/62.jpg",
    age: 47,
    address: "89427 Pandrup Haveforeningen Kildegården",
    password: "scooby1",
    rating: 0,
  },
];
